### ISSUE TITLE
Want to get the encoding format supported by the camera

### ISSUE THREAD

**Issue by LiYajun** [jtfrey/uvc-util#13]

**Comment by scchn** [comment]
Have you tried using [AVCaptureDevice](https://developer.apple.com/documentation/avfoundation/avcapturedevice)?

**Comment by LiYajun** [comment]
Thanks for reminding, I have got it.
At first I wanted to get the information through the command line, but I couldn't find a way.
The following code works for me:(Mac OS 10.15.5, xcode Version 12.2 (12B45b))

    [AVCaptureDevice requestAccessForMediaType: AVMediaTypeVideo completionHandler:^(BOOL granted) {
             
        AVCaptureDeviceDiscoverySession* s = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:@[AVCaptureDeviceTypeExternalUnknown]
                                                                                                    mediaType:AVMediaTypeVideo
                                                                                                     position:AVCaptureDevicePositionUnspecified];
        NSArray* devices = s.devices;
       
        for(AVCaptureDevice* dev in devices){
            if([dev.localizedName containsString:@"eEver USB Device"]){
                NSArray<AVCaptureDeviceFormat*>* supportFormats = dev.formats;
                NSLog(@"eEver USB Device support formats: %@",  supportFormats);
            }
        }
    }];
Note: Please add “Privacy-Camera Usage Description” key to info.plist and add “Camera” key with “YES” to the entitlements file.
