### ISSUE TITLE
macOS Monterey: uvc-util finds UVC devices but no capabilities

### ISSUE THREAD

**Issue by bplein** [jtfrey/uvc-util#14]
2017 iMac Pro
macOS Monterey beta

UVC Util worked fine with Big Sur.

```
 bill@godzilla  ~/bin  uvc-util -d
------------ -------------- ------------ ------------ ------------------------------------------------
Index        Vend:Prod      LocationID   UVC Version  Device name
------------ -------------- ------------ ------------ ------------------------------------------------
0            0x534d:0x2109  0x14513400   1.00         IOUSBHostDevice
1            0x1532:0x0e03  0x14513300   1.00         Razer Kiyo
------------ -------------- ------------ ------------ ------------------------------------------------
 bill@godzilla  ~/bin  uvc-util -I 1 -c
UVC controls implemented by this device:
 bill@godzilla  ~/bin  uvc-util -I 0 -c
UVC controls implemented by this device:
 bill@godzilla  ~/bin 

```

**Comment by scchn** [comment]
> The program was written for another IT unit I was helping at the time, so I am not maintaining this program moving forward. I encourage other developer(s) to take over.

This project is great and easy to use, but I'm not sure there will be any updates.

---

I have the same needs of UVC thing,  so I made a little project that built on [libuvc](https://github.com/libuvc/libuvc).
But my machine is too old to install Monterey, if you're interested you can try and let me know it works or not.

[https://github.com/scchn/libuvc-test](https://github.com/scchn/libuvc-test)

**Comment by bplein** [comment]
I'll take a look. Thanks!

**Comment by scchn** [comment]
@bplein 
I created a new repo, hope it helps.
[https://github.com/scchn/CamPrefs](https://github.com/scchn/CamPrefs)

**Comment by volsk** [comment]
Same issue

**Comment by andreasfertig** [comment]
Hello all,

please  have a look at my fork https://github.com/andreasfertig/uvc-util/releases/ which at least works for me under Monterey.

Andreas

**Comment by jtfrey** [comment]
Please see:   https://github.com/kovidgoyal/kitty/issues/3719

That issue log includes this code:

```
#if (MAC_OS_X_VERSION_MAX_ALLOWED < 120000) // Before macOS 12 Monterey
  #define kIOMainPortDefault kIOMasterPortDefault
#endif
```

that allows the source to use `kIOMainPortDefault` throughout and on earlier versions (where it isn't defined) use the now-deprecated `kIOMasterPortDefault`.  I'll patch my repository with that addition and change.

**Comment by jtfrey** [comment]
One other issue is w.r.t. the `USBInterfaceOpen()` function on an interface:  when already opened, the API will (12.0 and onward) return the `kIOReturnExclusiveAccess` code:  this is not necessarily indicative of an error, it's more like a warning.  So the `setIsInterfaceOpen:` method needed to be altered to react to that condition, too.  With that additional modification to the source, my daughter's little apeMan USB camera was controllable:

```
▶ ./uvc-util -d     
------------ -------------- ------------ ------------ ------------------------------------------------
Index        Vend:Prod      LocationID   UVC Version  Device name
------------ -------------- ------------ ------------ ------------------------------------------------
0            0x2aad:0x6373  0x01111000   1.00         iCatch V37
------------ -------------- ------------ ------------ ------------------------------------------------

▶ ./uvc-util -I 0 -c
UVC controls implemented by this device:
  white-balance-temp
  exposure-time-abs
  auto-focus
  auto-exposure-priority
  auto-exposure-mode
  auto-white-balance-component
  focus-abs
  
▶ ./uvc-util -I 0 -g auto-focus
auto-focus = false

▶ ./uvc-util -I 0 -s auto-focus=true

▶ ./uvc-util -I 0 -g auto-focus     
auto-focus = true
```

**Comment by BeansIsFat** [comment]
I just compiled your latest commit on Monterey (12.5) and it doesn't list any UVC controls for my device.

The build from andreasfertig worked.

**Comment by jtfrey** [comment]
I hadn't pushed all the changes up to github yet when you tried it.  Please try commit ebb24022ee9693fbeb23e768a5b06379069571a6.

**Comment by BeansIsFat** [comment]
I just noticed the same. I pulled the latest commit and it's working now. Thank you.

**Comment by andreasfertig** [comment]
Hello @jtfrey,

perfect, thanks for fixing this! I think I can remove my fork to avoid confusion.

Andreas

**Comment by jtfrey** [comment]
That's the first time my code has been impacted by politically-correct alterations to an API 😄

**Comment by bplein** [comment]
Works for me
