### ISSUE TITLE
Cannot detect any webcam in macOS Catalina 10.15

### ISSUE THREAD

**Issue by gordonel** [jtfrey/uvc-util#2]
HI @jtfrey. Thanks for the app.

I've been trying to find out the the app is broken on Catalina, but to no avail. It cannot detect any webcams whatsoever. Please, can you take a look?

**Comment by jtfrey** [comment]
Not all webcams can be controlled via UVC.  E.g. on my 2014 MacBook Pro:

```
$ ./uvc-util --list-devices
ERROR:  no UVC-capable devices available
```

That laptop model definitely has an integrated camera, it's just not a USB camera.

**Comment by gordonel** [comment]
@jtfrey I'm afraid there's a misunderstanding here.

I had everything working on Mojave and I could control the built-in webcam. I also have Logitech Brio connected, which is a UVC-capable webcam. In Catalina, I can to longer control it

**Comment by gordonel** [comment]
UPD: updated to the latest master. Now it can see the camera but doesn't list any controls

**Comment by jtfrey** [comment]
Perhaps Apple changed the USB camera driver or the parameters it exposes to applications — that happens.  I don't have access to the cameras I used to write and test this program back when I wrote it.  Feel free to fork and add fixes for Catalina.
