### ISSUE TITLE
Segmentation Fault when listing cameras

### ISSUE THREAD

**Issue by wackazong** [jtfrey/uvc-util#3]
Laptop:Desktop ander$ ./uvc-util -d
    ------------ -------------- ------------ ------------ ------------------------------------------------
    Index        Vend:Prod      LocationID   UVC Version  Device name
    ------------ -------------- ------------ ------------ ------------------------------------------------
    0            0x046d:0x086b  0x00200000   1.00         BRIO 4K Stream Edition
    ------------ -------------- ------------ ------------ ------------------------------------------------
    Segmentation fault: 11

**Comment by jtfrey** [comment]
The list of devices is loaded on-demand when needed in the main() function.  In the list-devices code the returned NSArray was not retain'ed, while in the other three command paths it was.  At the end of the main() function that array is release'd, which was unbalanced with the un-retain'ed instance.  Fixed.

**Comment by wackazong** [comment]
Thanks for that!
